name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  aws:
    runs-on: ubuntu-latest
    steps: 
      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_UPLOAD_S3 }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
      - name: deploy
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync --delete --cache-control 'public,max-age=31536000,immutable' ./_site/ s3://www.pureooze.com
